#ifndef SEQUENCEVIEWDEF_H
#define SEQUENCEVIEWDEF_H


enum class SequenceEditMode{
	EDIT_MODE,
	WRITE_MODE,
	INTERACTIVE_MODE,
};

enum class SequenceEditSelection{
	NO_SELECTION,
	KEY_SOUND_NOTES_SELECTION,
	BGM_SOUND_NOTES_SELECTION,
	BPM_EVENTS_SELECTION,
};

#endif // SEQUENCEVIEWDEF_H

